stages:
  - build_stage
  - deploy_stage

build:
  stage: build_stage
  script:
    - apt update -y
    - apt install npm -y
    - apt install
  artifacts:
    paths:
      - node_modules
      - package-lock.json

deploy:
  stage: deploy_stage
  script:
  - apt update -y
  - apt install nodejs -y
  - node app.js